apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-cluster-role-binding-xfusion
  namespace: haproxy-controller-xfusion
subjects:
- kind: ServiceAccount
  name: haproxy-service-account-xfusion
  namespace: haproxy-controller-xfusion
roleRef:
  kind: ClusterRole
  name: haproxy-cluster-role-xfusion
  apiGroup: rbac.authorization.k8s.io
