apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-xfusion
  namespace: haproxy-controller-xfusion
  labels:
    run: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-service-account-xfusion
      containers:
      - name: ingress-container-xfusion
        image: haproxytech/kubernetes-ingress
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
        command: ["/bin/sh"]
        args: 
        - --default-backend-service=haproxy-controller-xfusion/service-backend-xfusion
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1024
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: TZ
          value: Etc/UTC
        - name: POD_NAME
          valueFrom:
            fieldRef: 
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef: 
              fieldPath: metadata.namespace
      
